### ISSUE TITLE
[Bug]: Cayo Perico skip cooldown not working

### ISSUE THREAD

**Issue by Samppaxx** [YimMenu/YimMenuV2#135]
### Describe the bug

nothing happens when pressed.

### Steps To Reproduce

hmm

### Expected Behavior

hmm

### Store

Epic Games

### Anticheat bypass mode

Without FSL

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenuV2

**Comment by ThrexeL** [comment]
I think it won't take effect until you go to Story mode and then back to Online.

**Comment by xZueS19** [comment]
> I think it won't take effect until you go to Story mode and then back to Online.

yes you must go to story then come back online @Samppaxx

**Comment by Samppaxx** [comment]
Seems to fix the problem... Thanks.

**Comment by maybegreat48** [comment]
The cooldown should be skipped now whether or not you restart your game

**Comment by xZueS19** [comment]
with the new dll i get this error in the log when i inject

![Image](https://github.com/user-attachments/assets/6659338b-df82-46f3-954b-1d442f5d6452)
is it okey ? @maybegreat48

**Comment by maybegreat48** [comment]
>  is it okey ? @maybegreat48 

Can you send me your socialclub.dll?

**Comment by xZueS19** [comment]
[socialclub.zip](https://github.com/user-attachments/files/19672663/socialclub.zip)

> > is it okey ? [@maybegreat48](https://github.com/maybegreat48)
> 
> Can you send me your socialclub.dll?

here it is

**Comment by ThrexeL** [comment]
> with the new dll i get this error in the log when i inject
> 
> ![Image](https://github.com/user-attachments/assets/6659338b-df82-46f3-954b-1d442f5d6452) is it okey ? [@maybegreat48](https://github.com/maybegreat48)

Yeah, I just tried the new update and have the same issue.

**Comment by maybegreat48** [comment]
> where can i find it ?

`C:\Program Files\Rockstar Games\socialclub` I think

**Comment by xZueS19** [comment]
> > where can i find it ?
> 
> `C:\Program Files\Rockstar Games\socialclub` I think

[socialclub.zip](https://github.com/user-attachments/files/19672685/socialclub.zip)

**Comment by maybegreat48** [comment]
Your social club DLL is seemingly newer than mine

**Comment by xZueS19** [comment]
> Your social club DLL is seemingly newer than mine

There was an update for the launcher this morning or yesterday i cant remember exactly

**Comment by maybegreat48** [comment]
This will be fixed in my next commit. Thanks for reporting

**Comment by maybegreat48** [comment]
Should be fixed now

**Comment by ThrexeL** [comment]
> Should be fixed now

Yes, it's fixed now. Thank you very much! 👍

**Comment by xZueS19** [comment]
the skip cooldown issue has returned again, and now even when i go to story mode then online it says pavel will contact u when it's available

**Comment by RamRamRoo** [comment]
still doesn't work well for me

nothing happen when I press cooldown skip
It skipped after I go story mode and back to online

after that, There's no secondary targets, and 0 value of them

**Comment by xZueS19** [comment]
> still doesn't work well for me
> 
> nothing happen when I press cooldown skip It skipped after I go story mode and back to online
> 
> after that, There's no secondary targets, and 0 value of them

there's like 5 min cool down i think to it and for the 0 second target => https://github.com/YimMenu/YimMenuV2/issues/137#issuecomment-2790583091
