### ISSUE TITLE
[Bug]: Unable to inject after 15M

### ISSUE THREAD

**Issue by basicbroccolii** [YimMenu/YimMenuV2#339]
### Describe the bug

Game fails to load, story or online doesn't matter.
The second injection seems to happen, the game crashes.

The game obviously launches without injection just fine.

The only actual instance of something being changed is the money I've gained through the recovery section, 3x 5M but other than that no hard changes, menu is usually used to teleport around.

------------------------------------------------

### Steps To Reproduce

For me.

Start Xenos/64x > Start Game > Main Menu.

Process Selection > Existing 
Process > GTA5_Enhanced.exe

Images > YimMenuV2.dll (most recent, 19h)

[12:55:03.6137608][ERROR/ExceptionHandler.cpp:45] 3B800000 Size: 36864
bcryp
Dumping registers:
RAX: 0x0
RCX: 0xFFFFFFFFFD2C2A30
RDX: 0x0
RBX: 0x1FA6547D5D0
RSI: 0x20
RDI: 0x1FA653B6C40
RSP: 0x69A1BFF080
RBP: 0x7FF78414B0F6
R8:  0x0
R9:  0x7FF930E24078
R10: 0x0
R11: 0x69A1BFF020
R12: 0x90E3240
R13: 0x0
R14: 0x2
R15: 0x90E3230
Dumping stacktrace:
[0]     YimMenuV2.dll+0x241EEB 0x7FF930C21EEB
[1]     YimMenuV2.dll+0x2405E2 0x7FF930C205E2
[2]     YimMenuV2.dll+0x23FAED 0x7FF930C1FAED
[3]     YimMenuV2.dll+0x257598 0x7FF930C37598
[4]     YimMenuV2.dll+0xCB04D 0x7FF930AAB04D
[5]     YimMenuV2.dll+0xC4433 0x7FF930AA4433
[6]     YimMenuV2.dll+0xCB939 0x7FF930AAB939
[7]     YimMenuV2.dll+0xCCD73 0x7FF930AACD73
[8]     YimMenuV2.dll+0xCD918 0x7FF930AAD918
[9]     YimMenuV2.dll+0xD038C 0x7FF930AB038C
[10]    YimMenuV2.dll+0xCE674 0x7FF930AAE674
[11]    YimMenuV2.dll+0xCBA28 0x7FF930AABA28
[12]    MSVCP140.dll Concurrency::details::_Schedule_chore (MSVCP140.dll+0x12B09)
[13]    ntdll.dll RtlRaiseStatus (ntdll.dll+0x90CE0)
[14]    ntdll.dll RtlAcquireSRWLockExclusive (ntdll.dll+0x7D7A1)
[15]    KERNEL32.DLL BaseThreadInitThunk (KERNEL32.DLL+0x2E8D7)
[16]    ntdll.dll RtlUserThreadStart (ntdll.dll+0x9C5DC)
Attempted to write to 0x1FA62740008

--------End of exception--------

-----------------------------------
### Expected Behavior

Expected to load into GTAV:E Online with the menu injected, instead it crashes due fail to inject or some other factor.

[cout.log](https://github.com/user-attachments/files/20430974/cout.log)

### Logs and/or screenshots

```
Quite a big file, I've attached log to bug report.
```

### Store

Epic Games

### Anticheat bypass mode

With FSL

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenuV2

**Comment by eXhumer** [comment]
Delete the .bin files from `%APPDATA%/YimMenu` and inject. You might need to do it everytime the YimMenu is updated.

**Comment by basicbroccolii** [comment]
Issue apparently solved by deleting .bin after every usage of YimMenu!

**Comment by tupoy-ya** [comment]
We should just disable pointer cache until someone figures out how to fix it.

**Comment by maybegreat48** [comment]
> We should just disable pointer cache until someone figures out how to fix it.

I'm not sure why it works for some people and doesn't for others

**Comment by maybegreat48** [comment]
This has been fixed now

**Comment by eXhumer** [comment]
While the game doesn't crash anymore from re-injecting without deleting the .bin files, but still throws two `EXCEPTION_ACCESS_VIOLATION`s and sig scanner warning similar to #317.

![Image](https://github.com/user-attachments/assets/36e0f3ec-4ecf-4379-9f54-5a4fd5a92d0d)

Full log: [cout.txt](https://github.com/user-attachments/files/20519247/cout.txt)

**Comment by eXhumer** [comment]
No sig scanner issue when deleting the .bin files and injecting.

**Comment by eXhumer** [comment]
The sig scanner thing seems related to being in pause menu in story mode. Moving to online, it doesn't seem to appear.

**Comment by JJGUY123456** [comment]
> The sig scanner thing seems related to being in pause menu in story mode. Moving to online, it doesn't seem to appear.

For me the "sig scanner" error appears in online too, and then after a while the game crashes.
